"""add_resume_ingestion_tables

Revision ID: 98ed618ac695
Revises: 456695fe3d7f
Create Date: 2026-05-15 18:27:52.220834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ed618ac695'
down_revision: Union[str, Sequence[str], None] = '456695fe3d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_certifications_employee_id'), 'employee_certifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_certifications_id'), 'employee_certifications', ['id'], unique=False)
    op.create_table('employee_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('technologies', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_projects_employee_id'), 'employee_projects', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_projects_id'), 'employee_projects', ['id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('proficiency', sa.String(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=True),
    sa.Column('is_inferred', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_id'), 'employee_skills', ['id'], unique=False)
    op.create_table('pending_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('original_pdf_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_profiles_employee_id'), 'pending_profiles', ['employee_id'], unique=False)
    op.create_index(op.f('ix_pending_profiles_id'), 'pending_profiles', ['id'], unique=False)
    op.add_column('employees', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('domain_expertise', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'domain_expertise')
    op.drop_column('employees', 'years_of_experience')
    op.drop_column('employees', 'summary')
    op.drop_index(op.f('ix_pending_profiles_id'), table_name='pending_profiles')
    op.drop_index(op.f('ix_pending_profiles_employee_id'), table_name='pending_profiles')
    op.drop_table('pending_profiles')
    op.drop_index(op.f('ix_employee_skills_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_employee_projects_id'), table_name='employee_projects')
    op.drop_index(op.f('ix_employee_projects_employee_id'), table_name='employee_projects')
    op.drop_table('employee_projects')
    op.drop_index(op.f('ix_employee_certifications_id'), table_name='employee_certifications')
    op.drop_index(op.f('ix_employee_certifications_employee_id'), table_name='employee_certifications')
    op.drop_table('employee_certifications')
    # ### end Alembic commands ###
