"""add_uploaded_by_to_pending_profiles

Revision ID: c07c1a796fd8
Revises: 98ed618ac695
Create Date: 2026-05-16 00:15:21.003347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07c1a796fd8'
down_revision: Union[str, Sequence[str], None] = '98ed618ac695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_profiles', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pending_profiles', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_profiles', type_='foreignkey')
    op.drop_column('pending_profiles', 'uploaded_by')
    # ### end Alembic commands ###
